### PR TITLE
 add no-wrap option for labels in form

### PR DESCRIPTION
**Pull request by Misko-2083**
--no-wrap for LBL form fields

### CODE REVIEW

**Comment by step-** [comment]
Thank you for this PR. I couldn't find this same option in https://github.com/v1cont/yad so I'm reluctant to add it to this fork. This isn't to say that I won't but I need some discussion.
Are you going to submit this feature to v1cont's repo, as well? That would be my preference.
What's your use case? Why do you need this feature?
Thanks again

**Comment by Misko-2083** [comment]
The discussion and use case are on the forum https://forum.puppylinux.com/viewtopic.php?p=62759#p62759
Maybe a few pages before that.
I never needed it so far, Mochi complained about --field="":LBL expanding on long labels.

**Comment by step-** [comment]
Mochi doesn't use this fork, AFAIK.

**Comment by Misko-2083** [comment]
And I thought all the puppies use your gtk2 fork.
That part of the code is almost the same as Vika's  @v1cont
https://github.com/v1cont/yad/blob/master/src/form.c#L1265
And wrapping happens in yad version 12.
If it doesn't happen with Mochi's fork it may have been an old bug.

**Comment by Misko-2083** [comment]
In a very bad way too in v12. It increases the height of a window.
```bash
TEXT="<span bgcolor='#f88' font='64'>1 2 3 4 5 6 7 8 9 10 11</span>"
yad --form --field="$TEXT":LBL --geometry 500x150
```

**Comment by step-** [comment]
My test results: https://forum.puppylinux.com/viewtopic.php?p=62766#p62766

**Comment by Misko-2083** [comment]
I'll close this MR for now.

**Pull request closed without merging**
